CREATE TABLE MEMBERS
(NAME CHAR(20) NOT NULL,
 AGE INTEGER,
 OCCUPATION_STATUS CHAR(20),
 GAMES_PLAYED_FREQUENTLY CHAR(20)
 );
 INSERT INTO MEMBERS(NAME, AGE, OCCUPATION_STATUS, GAMES_PLAYED_FREQUENTLY)
 VALUES
 ('CHRIS',20,'STUDENT','HOCKEY'),
 ('HENRY',30,'WORKING','BGMI'),
 ('MARK',16,'STUDENT','CRICKET'),
 ('LOUIS',17,'STUDENT','RUGBY'),
 ('AHMED',33,'WORKING','FOOTBALL'),
 ('ROMARIO',20,'STUDENT','SOCCER'),
 ('LIAM',29,'WORKING','GOLF'),
 ('HUGH',30,'NONE','CHESS'),
 ('MIKE',14,'STUDENT','HOCKEY');
 
  UPDATE MEMBERS
  SET NAME='JUNAID',OCCUPATION_STATUS='FIGHTER',AGE=21
 WHERE NAME='CHRIS';
 
 UPDATE MEMBERS
 SET OCCUPATION_STATUS="RETIRED"
 WHERE NAME = 'HUGH';
 SELECT * FROM MEMBERS
 